### ISSUE TITLE
How to start an arduino compiled code from here

### ISSUE THREAD

**Issue by smartelements** [gtxzsxxk/milkv-duo-smallcore-freertos#2]
Hi, 
I am new to Milk-v duo and just tested first arduino sketches. Since the arduino.elf is loaded and started AFTER the linux core has completely booted I wonder how can I boot the arduino code immediately after power up ?

**Comment by gtxzsxxk** [comment]
Hi, I am new to the arduino on milk-v duo as well. Do you mean that you want to run the machine code which is artifacts of the arduino IDE on the small core? If so, please seek some hints from

https://github.com/milkv-duo/duo-buildroot-sdk 

and especially,

https://github.com/milkv-duo/milkv-duo-buildroot/blob/c898cb9996289bf6378aa5366194316219da3da3/board/milkv/duo/post-image.sh

by how they integrate the small core binary code into the `fip.bin`.

**Comment by smartelements** [comment]
Hi, thank you for your fast response. My main question is: Can I take advantage of the short booting time of the little core and execute simple led blink sample as soon as the CPU is powered on without waiting 15 or 20 secs until the linux core has fully booted? Next step would be accessing the SD card and loading the arduino.elf file into the memory and execute it long before linus has started. OR is the little core fully dependend of the linux core and does not function independently?

**Comment by gtxzsxxk** [comment]
> Can I take advantage of the short booting time of the little core and execute simple led blink sample as soon as the CPU is powered on without waiting 15 or 20 secs until the linux core has fully booted?

I have not been in touch with milk-v duo for almost one year. I just checked its document and I guess this LED blinking is no more the linux-gpio-subsystem-based-user-script-driven version anymore. Is this LED blinking now driven by the small core and relied on the linux kernel's mailbox mapped as a sysfs, which is then driven by an user script?

If so, if you want to let it blink as soon as the cpu is power on, I believe you could have a try that you could modify the u-boot's source code, integrate the cvitek's big/small core mailbox's driver into u-boot. I have checked that this driver is very simple, only some MMIO operations.

linux_5.10/drivers/soc/cvitek/rtos_cmdqu/

> Next step would be accessing the SD card and loading the arduino.elf file into the memory and execute it long before linus has started. OR is the little core fully dependend of the linux core and does not function independently?

This is exactly what u-boot should do. But I worry that, given the small core program is previous loaded via the `fip.bin`, do the small/big cores share the same addressing space? We don't know the SoC's detailed information, and we must make sure whether we can write the memory which the small core is executing on, and change its program counter. If the two is possible, then you can make it in u-boot.

**Comment by smartelements** [comment]
I have no idea how to modify the u-boot. I would be happy to let the led blink on power up before linux started. My main idea was to drive an lcd display with a splash screen that informs that linux is loading... For this reason I need the little core to do something right after power on. I do not need the mailbox driver since the little core should work independently and do its own things. Probably this is not possible?

**Comment by gtxzsxxk** [comment]
It is possible but a little bit hard core because you cannot get rid of reading the friendly source code.

**Comment by smartelements** [comment]
Hello,I need to use I2C1 port in freertos on the milkv-duo256m to drive an lcd display. I still have no idea about the pinmux concept and tried for several days to figure ut out. How do I configure GP4 and GP5 as I2C_SDA and I2C_SCL?Thank you for your help.Best regards Juergen BauerVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: gtxzsxxk ***@***.***> Datum: 15.10.24  02:34  (GMT+01:00) An: gtxzsxxk/milkv-duo-smallcore-freertos ***@***.***> Cc: smartelements ***@***.***>, Author ***@***.***> Betreff: Re: [gtxzsxxk/milkv-duo-smallcore-freertos] How to start an arduino compiled code from here (Issue #2) 
It is possible but a little bit hard core because you cannot get rid of reading the friendly source code.

**Comment by gtxzsxxk** [comment]
Hi, you must be able to seek all answers to your questions, by reading the source code from the duo repo. To me, the code they leaked out are very complete.
